### ISSUE TITLE
Question about accessing shader code dataset & license

### ISSUE THREAD

**Issue by prixt** [mbaradad/shaders21k#1]
Hi, I want to utilize procedurally generated images to train generative models, and your paper and research appear to be very relevant to this! Two questions regarding access to the dataset:

1. What form will I have to fill out to access the pre-packed shader codes?
2. And under what license are you planning on releasing the shader code dataset?

Thank you!

**Comment by mbaradad** [comment]
Hi, thanks for your interest.
1) For now, we provide the codes by request to the authors (through an email), we will make it automatic with a form in the future.
2) The shaders are publicly available in shadertoy and twitter, and come with their associated licenses. Shadertoy code are associated with the following license by default: https://www.shadertoy.com/terms while general twitter license applies for twigl code.

**Comment by priyamdey** [comment]
Hi @mbaradad , is the form to request for the shader code dataset publicly available now, or do we have to request it via email? 

Thanks

**Comment by tomoki87** [comment]
Hi @mbaradad , I am facing the same problem. Could you please let me know if there is a request form so I can access it too? Thank you in advance.

**Comment by mbaradad** [comment]
Hi, for issues regarding access, send me an email. Thanks!
