### ISSUE TITLE
shader ids

### ISSUE THREAD

**Issue by seekingdeep** [mbaradad/shaders21k#2]
Hi there
the shader ids are empty,
how to get them

**Comment by es-eph** [comment]
Hello, 

I am also interested in the shaders list that was used to train the model. 

Thanks.

**Comment by mbaradad** [comment]
Hi, we have added the codes as a download, and the shader information is now included. The script to download the shaders is:

https://github.com/mbaradad/shaders21k/blob/main/scripts/download/download_shader_codes.sh
